blueprint:
  name: Basic Light Remote
  description: > 
    Control a light with a remote.

    v0.0.1
  domain: automation
  author: arfejes
  source_url: https://raw.githubusercontent.com/arfejes/homeassistant_shared/refs/heads/light-remote-basic-control/blueprints/automation/arfejes/light_remote_basic_control.yaml
  input: 
    target_light:
      name: Light
      description: Select the lamp to be controlled.
      selector:
        entity:
          domain:
            - light
#    trigger_on:
#      name: Trigger On
#      description: The trigger that will turn the lamp on. 
#      selector:
#        trigger: {}
#    trigger_off:
#      name: Trigger Off
#      description: The trigger that will turn the lamp off. 
#      selector:
#        trigger: {}
    trigger_toggle:
      name: Trigger to toggle lamp
      description: The trigger that will toggel the lamp. 
      selector:
        trigger: {}
    trigger_dim_up:
      name: Trigger to dim up
      description: The trigger that will make the lamp brighter. 
      selector:
        trigger: {}
    trigger_dim_down:
      name: Trigger to dim
      description: The trigger that will make the lamp dimmer. 
      selector:
        trigger: {}


mode: queued
max: 3

trigger:
#  - triggers:
#    entity_id: !input trigger_on
#    id: trigger_on
#  - triggers:
#    entity_id: !input trigger_off
#    id: trigger_off
  - entity_id: !input trigger_toggle
    id: trigger_toggle
  - entity_id: !input trigger_dim_up
    id: trigger_dim_up
  - entity_id: !input trigger_dim_down
    id: trigger_dim_down


conditions: []
actions:
  - variables:
      lamp: !input target_light
  - if:
      - condition: trigger
        id:
          - trigger_dim_up
    then:
      - domain: light
        entity_id: "{{ lamp }}"
        type: brightness_increase
  - if:
      - condition: trigger
        id:
          - trigger_dim_down
    then:
      - domain: light
        entity_id: "{{ lamp }}"
        type: brightness_decrease
  - if:
      - condition: trigger
        id:
          - trun_on
    then:
      - domain: light
        entity_id: "{{ lamp }}"
        type: toggle

