blueprint:
  name: Basic Light Remote
  description: > 
    Control a light with a remote.

    v0.0.1-2
  domain: automation
  author: arfejes
  source_url: https://raw.githubusercontent.com/arfejes/homeassistant_shared/refs/heads/light-remote-basic-control/blueprints/automation/arfejes/light_remote_basic_control.yaml
  input: 
    target_light:
      name: Light
      description: Select the lamp to be controlled.
      selector:
        entity:
          domain:
            - light
#    trigger_on:
#      name: Trigger On
#      description: The trigger that will turn the lamp on. 
#      selector:
#        trigger: {}
#    trigger_off:
#      name: Trigger Off
#      description: The trigger that will turn the lamp off. 
#      selector:
#        trigger: {}
    trigger_toggle:
      name: Trigger to toggle lamp
      description: The trigger that will toggel the lamp. 
      selector:
        trigger: {}
    trigger_dim_up:
      name: Trigger to dim up
      description: The trigger that will make the lamp brighter. 
      selector:
        trigger: {}
    trigger_dim_down:
      name: Trigger to dim
      description: The trigger that will make the lamp dimmer. 
      selector:
        trigger: {}


mode: queued
max: 3

trigger:
  !input trigger_toggle
  !input trigger_dim_up
  !input trigger_dim_down


conditions: []
actions:
  - if:
      - condition: trigger
        id:
          - trigger_dim_up
    then:
      - action: light.turn_on
        target:
          entity_id: !input target_light
        data:
          brightness_step_pct: 10
          transition: 0.2
  - if:
      - condition: trigger
        id:
          - trigger_dim_down
    then:
      - action: light.turn_on
        target:
          entity_id: !input target_light
        data:
          brightness_step_pct: -10
          transition: 0.2
  - if:
      - condition: trigger
        id:
          - trigger_toggle
    then:
      - action: light.toggle
        target:
          entity_id: !input target_light

